pipeline:
  name: my-first-harness-pipeline-as-code
  identifier: myfirstharnesspipelineascode
  projectIdentifier: DotNetDemo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitHubJoostvdg
        build: <+input>
  stages:
    - stage:
        name: HelloWOrld
        identifier: HelloWOrld
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: echo "Hello World!"
